solver_options:
    regularization: 1e-4
    back_end: qpoases

stack:
    - [meca_B]
    - [Postural]

# constraints: [JointLimits, VelocityLimits]
constraints: [JointLimits]

meca_B:
    type: Cartesian
    distal_link: meca_axis_6_link_B
    base_link: base_link_B
    # control_mode: Velocity
    lambda: 0.1
    name: meca_B
    # indices: [0, 1, 2]

JointLimits:
    type: JointLimits


VelocityLimits:
    type: VelocityLimits

Postural:
    type: Postural
    lambda: 0.01
    weight: 0.001