solver_options:
    regularization: 1e-4
    back_end: qpoases

stack:
    - [meca_A, meca_B]
    - [Postural]

constraints: [JointLimits, VelocityLimits]

meca_A:
    type: Cartesian
    distal_link: meca_axis_6_link_A
    base_link: meca_base_link_A
    # control_mode: Velocity
    lambda: 0.1
    name: meca_A
    # indices: [0, 1, 2]

meca_B:
    type: Cartesian
    distal_link: meca_axis_6_link_B
    base_link: meca_base_link_B
    # control_mode: Velocity
    lambda: 0.1
    name: meca_B
    # indices: [0, 1, 2]

JointLimits:
    type: JointLimits


VelocityLimits:
    type: VelocityLimits

Postural:
    type: Postural
    lambda: 0.01
    weight: 0.001