solver_options:
    regularization: 1e-4
    back_end: qpoases

stack:
    - [ArmPose]

    
constraints: [JointLimits, VelocityLimits]

ArmPose:
    type: Cartesian
    distal_link: meca_axis_6_link
    lambda: 0.1
    name: meca

JointLimits:
    type: JointLimits


VelocityLimits:
    type: VelocityLimits
